apiVersion: v1
kind: Template
metadata:
  annotations:
    description: ${SERVICE_NAME} build config template
  name: ${SERVICE_NAME}-build-config-template
parameters:
- description: Name of the service to be deployed
  displayName: Service Name
  name: SERVICE_NAME
- description: Git repository where service is stored
  displayName: GIT Service URL
  name: SERVICE_GIT_URL
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${SERVICE_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${SERVICE_NAME}:latest
    source:
      contextDir: /
      git:
        ref: master
        uri: ${SERVICE_GIT_URL}
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: GIT_SSL_NO_VERIFY
            value: 'true'
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: '0'
        from:
          kind: ImageStreamTag
          name: s2i-openshift-alpine-nodejs:latest
          namespace: drya024
      type: Source
    triggers:
    - type: Generic
      generic:
        secret: 41ECE3B7-A787-46FB-8C7B-BB7E53D88A23